name: Publish zen-mapper to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "zen/*"

jobs:
  publish:
    name: Build distribution
    environment:
      name: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      # Configure the runner
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      # Build
      - name: Build dist
        run: |
          nix develop --command \
            just zen build

      # Upload artifacts
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      # Publish
      - name: Publish to pypi
        run: |
          nix develop --command \
            just zen publish
